-- V5-WP19-B：把两个「被代码用到但不在枚举里」的配置键补进 SystemConfigName。
--
-- ENUM 取值由 schema 自动生成（`prisma migrate diff` 输出直落，手抄会与 schema 漂移）。
-- 追加在**末尾**是必须的：MySQL 的 ENUM 是序号存储，中间插值会让存量行错位。
-- 纯枚举扩值：可加操作，存量行不受影响；回滚只需停止读写这两个键。
-- AlterTable
ALTER TABLE `config` MODIFY `name` ENUM('MIN_TOPUP_AMOUNT', 'FAILOVER_POLICY', 'NOTICE', 'NOTICE_POPUP', 'NOTICE_POPUP_INTERVAL_HOURS', 'SITE_NAME', 'SITE_DESCRIPTION', 'ALLOW_REGISTER', 'LOGO_URL', 'HIDE_NODE_STATUS', 'AUTO_UPDATE_AGENT', 'CHATWOOT_BASE_URL', 'CHATWOOT_TOKEN', 'TUNNEL_TRAFFIC_RETENTION_DAYS', 'HIDE_FOOTER', 'HIDE_DOCS', 'LANDING_PAGE_URL', 'REFERRAL_COMMISSION_RATE', 'REFERRAL_FIRST_ONLY', 'REFERRAL_MODE', 'OBSERVER_PERIOD', 'EMAIL_PROVIDER', 'SMTP_HOST', 'SMTP_PORT', 'SMTP_SECURE', 'SMTP_USER', 'SMTP_PASS', 'SMTP_FROM', 'RESEND_API_KEY', 'RESEND_FROM', 'MIN_WITHDRAW_AMOUNT', 'WITHDRAW_METHODS', 'LIMIT_SCOPE', 'ENABLE_SUBSCRIPTION', 'BILLING_SETTLEMENT_TAKEOVER_MINUTES', 'LATENCY_RAW_RETENTION_HOURS', 'LATENCY_BUCKET_RETENTION_DAYS') NOT NULL;
