import type { Locale } from "@/lib/i18n";

const zh = {
  title: "加密隧道", subtitle: "管理可复用的入出口连接，在同一隧道中承载多条转发规则。",
  create: "创建 FXP 隧道", refresh: "刷新", loading: "正在读取隧道…", empty: "当前工作空间还没有加密隧道。",
  denied: "没有读取节点资源的权限。", readonly: "当前权限只允许查看隧道。", workspace: "请先选择工作空间。",
  name: "名称", ingress: "入口节点", egress: "出口节点", chooseNode: "选择节点", carrierPort: "节点间连接端口",
  carrierHint: "此端口位于出口节点，需允许入口节点访问 TCP 和 UDP；与业务监听端口分别设置。",
  nodesFailed: "节点列表读取失败，请刷新后重试。", noNodes: "需要两个角色合适且生命周期为启用的节点。",
  save: "保存", cancel: "取消", working: "正在处理…", edit: "编辑端点", deploy: "部署", rotate: "轮换密钥",
  retire: "删除隧道", refs: "引用规则", desired: "期望版本", applied: "已应用", notApplied: "尚未应用",
  generation: "部署版本", state: "部署状态", desiredState: "期望状态", appliedVersion: "已应用配置版本", actionDenied: "当前权限不允许此操作。", lease: "运行租约到期", expired: "租约已过期", leaseUnknown: "租约状态未知",
  noDeployment: "尚未部署", passiveHint: "已应用的配置中，入口没有启用的转发规则。", ackHint: "应用回执记录最近一次配置应用。当前运行状态以节点事实为准。",
  errorDetails: "查看错误详情", updateHint: "保存或调整规则会触发隧道重新应用，现有连接可能中断。应用失败时，请查看状态并重试。",
  deploymentState: "当前部署", statusPolicyBlocked: "工作空间策略阻止部署",
  policyBlockedHint: "当前授权或流量策略不允许继续使用隧道，运行租约不会续期。请检查工作空间授权和流量额度；策略恢复后，系统会重新应用配置。",
  zeroRefs: "删除隧道和轮换密钥仅允许零引用；暂停的规则仍计入引用。",
  endpointRetire: "隧道已部署。修改端点或连接端口前，先删除此隧道并创建新的隧道。",
  rotateZeroRefs: "轮换密钥前请先删除全部引用规则，避免两个节点分步切换影响业务。",
  appliedAck: "应用回执", runtimeState: "当前运行状态", stale: "运行事实已过期", passiveDesired: "已应用无业务监听配置",
  passiveLive: "入口待命：没有启用的规则", exited: "已退出", closed: "已停止", removed: "已移除", mismatch: "运行配置与期望不一致", absent: "未发现运行实例",
  addForward: "添加转发规则", editForward: "编辑转发规则", protocol: "业务协议", protocolLocked: "修改协议或监听范围需创建新规则；业务端口可以修改。",
  listenPort: "业务监听端口", listenHost: "监听范围", wildcard: "所有地址", loopback4: "仅本机 IPv4", loopback6: "仅本机 IPv6",
  targetHost: "目标地址", targetPort: "目标端口", limits: "本规则限额", limitHint: "0 表示本规则不限；仍受工作空间策略约束。",
  rateIn: "客户端 → 目标（字节/秒）", rateOut: "目标 → 客户端（字节/秒）", connections: "总并发连接数", perIp: "每个来源 IP 的并发连接数",
  noForwards: "此隧道尚未绑定转发规则。", enabled: "启用", suspended: "暂停", suspend: "暂停", resume: "恢复", retry: "重试部署", delete: "删除规则",
  revision: "规则修订", unknown: "未知", statusDraft: "未部署", statusPending: "等待应用", statusDeploying: "正在部署",
  statusActive: "已部署", statusDegraded: "部署异常", statusRetired: "已删除", statusRunning: "运行中", statusPassive: "无业务监听",
  statusError: "应用失败", statusSuspended: "已暂停", statusInactive: "未启用", statusFailed: "失败", statusRetiring: "正在删除", statusBlocked: "部署被阻止",
  disabled: "服务端尚未启用 FXP 隧道，操作未执行。", failed: "操作未确认，请刷新查看实际状态后重试。",
  readFailed: "读取失败，请重试。", conflict: "配置已被其他操作修改。请重新读取并打开编辑表单，再提交。",
  submitted: "请求已完成，状态已重新读取。", reload: "重新读取", code: "原因码", validation: "请检查名称、节点、地址和数值范围。",
  rotateHint: "轮换会重新部署整个隧道，影响以下数量的引用规则，并可能中断已有连接。",
  retireHint: "删除会停止两个节点上的隧道。必须先删除所有引用规则。",
  deleteHint: "删除此规则会停止它的业务监听。其他规则的配置会保留，应用过程中现有连接可能中断。",
  configSaved: "端点已保存，请部署以应用新版本。", target: "转发目标", listener: "业务监听", select: "查看隧道",
} as const;
type CopyKey = keyof typeof zh;
const en: Record<CopyKey, string> = {
  title: "Encrypted tunnels", subtitle: "Manage reusable entry-to-exit links and carry multiple forwarding rules on each tunnel.",
  create: "Create FXP tunnel", refresh: "Refresh", loading: "Loading tunnels…", empty: "This workspace has no encrypted tunnels.",
  denied: "You do not have permission to read node resources.", readonly: "Your permissions allow viewing only.", workspace: "Select a workspace first.",
  name: "Name", ingress: "Entry node", egress: "Exit node", chooseNode: "Select a node", carrierPort: "Inter-node connection port",
  carrierHint: "Allow the entry node to reach TCP and UDP on this exit-node port. Business listener ports are configured separately.",
  nodesFailed: "Could not read nodes. Refresh and retry.", noNodes: "Two active nodes with suitable roles are required.",
  save: "Save", cancel: "Cancel", working: "Processing…", edit: "Edit endpoints", deploy: "Deploy", rotate: "Rotate key",
  retire: "Delete tunnel", refs: "Referenced rules", desired: "Desired version", applied: "Applied", notApplied: "Not applied",
  generation: "Deployment version", state: "Deployment status", desiredState: "Desired state", appliedVersion: "Applied configuration version", actionDenied: "Your permissions do not allow this operation.", lease: "Runtime lease expires", expired: "Lease expired", leaseUnknown: "Lease status unknown",
  noDeployment: "Not deployed", passiveHint: "The applied configuration contains no enabled entry rules.", ackHint: "Apply acknowledgements record the latest configuration application. Current runtime state comes from node observations.",
  errorDetails: "View error details", updateHint: "Saving or changing a rule reapplies the tunnel. Existing connections may be interrupted. Check the status and retry if application fails.",
  deploymentState: "Current deployment", statusPolicyBlocked: "Deployment blocked by workspace policy",
  policyBlockedHint: "Current authorization or traffic policies prevent further tunnel use, so the runtime lease will not renew. Check workspace authorization and traffic allowance. Once the policy permits use again, the system will reapply the configuration.",
  zeroRefs: "Tunnel deletion and key rotation require zero references. Suspended rules still count.",
  endpointRetire: "This tunnel has been deployed. Delete it and create a new tunnel before changing endpoints or the connection port.",
  rotateZeroRefs: "Delete all referenced rules before rotating the key to avoid affecting traffic during the two-node switch.",
  appliedAck: "Apply acknowledgement", runtimeState: "Current runtime state", stale: "Runtime facts are stale", passiveDesired: "No-listener configuration applied",
  passiveLive: "Entry standing by: no enabled rules", exited: "Exited", closed: "Stopped", removed: "Removed", mismatch: "Runtime configuration differs from desired", absent: "No runtime instance observed",
  addForward: "Add forwarding rule", editForward: "Edit forwarding rule", protocol: "Business protocol", protocolLocked: "Create a new rule to change its protocol or listen scope. The business port can be edited.",
  listenPort: "Business listener port", listenHost: "Listen scope", wildcard: "All addresses", loopback4: "Local IPv4 only", loopback6: "Local IPv6 only",
  targetHost: "Target address", targetPort: "Target port", limits: "Rule limits", limitHint: "0 means no rule-specific limit. Workspace policies still apply.",
  rateIn: "Client → target (bytes/sec)", rateOut: "Target → client (bytes/sec)", connections: "Total concurrent connections", perIp: "Concurrent connections per source IP",
  noForwards: "No forwarding rules are bound to this tunnel.", enabled: "Enabled", suspended: "Suspended", suspend: "Suspend", resume: "Resume", retry: "Retry deployment", delete: "Delete rule",
  revision: "Rule revision", unknown: "Unknown", statusDraft: "Not deployed", statusPending: "Pending apply", statusDeploying: "Deploying",
  statusActive: "Deployed", statusDegraded: "Deployment degraded", statusRetired: "Deleted", statusRunning: "Running", statusPassive: "No business listener",
  statusError: "Apply failed", statusSuspended: "Suspended", statusInactive: "Disabled", statusFailed: "Failed", statusRetiring: "Deleting", statusBlocked: "Deployment blocked",
  disabled: "FXP tunnels are not enabled on the server. The operation was not performed.", failed: "The operation is unconfirmed. Refresh to check the actual state before retrying.",
  readFailed: "Could not load data. Retry.", conflict: "Another operation changed this configuration. Reload and reopen the editor before submitting.",
  submitted: "Request completed; status reloaded.", reload: "Reload", code: "Reason code", validation: "Check the name, nodes, addresses and numeric ranges.",
  rotateHint: "Rotation redeploys the entire tunnel and affects this number of referenced rules. Existing connections may be interrupted.",
  retireHint: "Deletion stops the tunnel on both nodes. Delete all referenced rules first.",
  deleteHint: "Deletion stops this rule's business listener. Other rule configurations remain. Existing connections may be interrupted during application.",
  configSaved: "Endpoints saved. Deploy to apply the new version.", target: "Forwarding target", listener: "Business listener", select: "View tunnel",
};
export type LinksCopy = Record<CopyKey, string>;
export function linksCopy(locale: Locale): LinksCopy { return locale === "en" ? en : zh; }
