import type { Locale } from "@/lib/i18n";

const zh = {
  maintenancePreview: "维护预览", previewEndpoints: "预览端点变更", previewKey: "预览密钥轮换", previewOperation: "预览操作",
  previewRun: "生成预览", previewClose: "关闭预览", previewResult: "只读维护方案", previewCandidate: "候选配置（未保存）",
  previewHint: "仅生成只读方案，不保存配置、不轮换密钥、不部署。在线维护执行器尚不可用，现有端点编辑和密钥轮换限制仍然有效。",
  previewPortHint: "候选端口尚未检查可用性，也未预留。端口列表不代表端口可用。",
  previewFailed: "预览失败，未进行任何更改。请检查输入，或刷新后重试。",
  previewConflict: "预览快照已变化，未进行任何更改。请刷新后重新生成预览。",
  previewDisabled: "服务端尚未启用 FXP 隧道预览，未进行任何更改。",
  previewStale: "预览已过期或快照不再匹配。请重新生成预览；未进行任何更改。",
  previewExpiry: "预览有效期至", previewHeldPorts: "当前持有端口", previewCandidatePorts: "候选端口（未预留）",
  previewActive: "期望启用引用", previewSuspended: "期望暂停引用（仍计入方案）", previewLiveUnknown: "当前 TCP 连接数和 UDP 映射数均未知；不是历史累计值。",
  previewImpact: "预期影响（不是执行结果）", previewTcpNone: "TCP：无预期变更影响", previewTcpReconnect: "TCP：需要重新连接",
  previewTcpDrain: "TCP：需要排空旧连接", previewUdpNone: "UDP：无预期变更影响", previewUdpRebuild: "UDP：需要重建映射",
  previewNoExecutor: "维护执行尚不支持。此方案不能执行，也不保证无中断。", previewNoChange: "端点未变化。",
  previewNotDeployed: "密钥轮换方案需要已部署的隧道。", previewRuntimeUnconfirmed: "当前运行状态尚未确认，不能据此执行维护。",
  previewStages: "规划阶段（未执行）", previewReserve: "预留候选端口", previewPrepareEgress: "准备出口", previewVerifyEgress: "验证出口",
  previewCutover: "切换入口", previewVerifyIngress: "验证入口", previewDrain: "排空旧连接", previewRetire: "退役旧部署", previewRelease: "释放旧端口",
  previewChanges: "变更项", previewKeyPreserved: "密钥保留", previewKeyRotated: "计划轮换密钥（尚未轮换）",
  previewRuntimeReady: "快照运行状态已确认（不代表可维护）", previewRuntimeNotReady: "快照运行状态未就绪", previewRuntimeUnknown: "快照运行状态未知",
  previewTooLarge: "维护预览超出安全显示上限（500 条引用、2048 个持有端口）。暂停引用不会被省略；未进行任何更改。请减少引用后重试。",
  previewPendingHint: "期望暂停的规则可能仍有旧部署流量，尤其是在暂停尚未应用或运行状态未确认时。期望引用数量不能证明业务监听已停止。",
  title: "加密隧道", subtitle: "管理可复用的入出口连接，在同一隧道中承载多条转发规则。",
  create: "创建 FXP 隧道", refresh: "刷新", loading: "正在读取隧道…", empty: "当前工作空间还没有加密隧道。",
  denied: "没有读取节点资源的权限。", readonly: "当前权限只允许查看隧道。", workspace: "请先选择工作空间。",
  name: "名称", ingress: "入口节点", egress: "出口节点", chooseNode: "选择节点", carrierPort: "节点间连接端口",
  carrierHint: "此端口位于出口节点，需允许入口节点访问 TCP 和 UDP；与业务监听端口分别设置。",
  nodesFailed: "节点列表读取失败，请刷新后重试。", noNodes: "需要两个角色合适且生命周期为启用的节点。",
  save: "保存", cancel: "取消", working: "正在处理…", edit: "编辑端点", deploy: "部署", rotate: "轮换密钥",
  retire: "删除隧道", refs: "引用规则", desired: "期望版本", applied: "已应用", notApplied: "尚未应用",
  generation: "部署版本", state: "部署状态", desiredState: "期望状态", appliedVersion: "已应用配置版本", actionDenied: "当前权限不允许此操作。", lease: "运行租约到期", expired: "租约已过期", leaseUnknown: "租约状态未知",
  noDeployment: "尚未部署", passiveHint: "已应用的配置中，入口没有启用的转发规则。", ackHint: "应用回执记录最近一次配置应用。当前运行状态以节点事实为准。",
  errorDetails: "查看错误详情", updateHint: "保存或调整规则会触发隧道重新应用，现有连接可能中断。应用失败时，请查看状态并重试。",
  deploymentState: "当前部署", statusPolicyBlocked: "工作空间策略阻止部署",
  policyBlockedHint: "当前授权或流量策略不允许继续使用隧道，运行租约不会续期。请检查工作空间授权和流量额度；策略恢复后，系统会重新应用配置。",
  zeroRefs: "删除隧道和轮换密钥仅允许零引用；暂停的规则仍计入引用。",
  endpointRetire: "隧道已部署。修改端点或连接端口前，先删除此隧道并创建新的隧道。",
  rotateZeroRefs: "轮换密钥前请先删除全部引用规则，避免两个节点分步切换影响业务。",
  appliedAck: "应用回执", runtimeState: "当前运行状态", stale: "运行事实已过期", passiveDesired: "已应用无业务监听配置",
  passiveLive: "入口待命：没有启用的规则", exited: "已退出", closed: "已停止", removed: "已移除", mismatch: "运行配置与期望不一致", absent: "未发现运行实例",
  addForward: "添加转发规则", editForward: "编辑转发规则", protocol: "业务协议", protocolLocked: "修改协议或监听范围需创建新规则；业务端口可以修改。",
  listenPort: "业务监听端口", listenHost: "监听范围", wildcard: "所有地址", loopback4: "仅本机 IPv4", loopback6: "仅本机 IPv6",
  targetHost: "目标地址", targetPort: "目标端口", limits: "本规则限额", limitHint: "0 表示本规则不限；仍受工作空间策略约束。",
  targets: "目标集", targetsOptIn: "启用多目标选择", targetsLegacy: "旧版单目标",
  targetsLegacyHint: "默认保留旧版单目标。主动启用后，才能配置目标顺序、选择策略和探测。",
  targetsHint: "按顺序配置 1–10 个不重复的地址与端口。首项始终同步为本规则的首选目标。",
  targetAddressHint: "地址与端口分开填写，如 www.example.com 和 443。IPv6 使用原始地址，如 2001:db8::1，不加方括号；不接受反斜杠或带端口的地址。",
  targetsKeepSetHint: "此规则已使用目标集。退回单目标时删除其余项，保留一项并保存完整目标集。",
  targetsValidation: "请检查表单：目标集需有 1–10 个不重复的地址与端口，地址不能带反斜杠、方括号或端口，IPv6 需为有效原始地址；端口为 1–65535，失败和恢复窗口为 10–3600 的整数秒。",
  targetIndex: "目标索引", targetFirst: "首项", addTarget: "添加目标", removeTarget: "删除目标", moveTargetUp: "上移", moveTargetDown: "下移",
  targetStrategy: "选择策略", strategyFallback: "按序回退", strategyRoundRobin: "轮询", strategyRandom: "随机",
  targetFailureSeconds: "连续失败窗口（秒）", targetRecoverSeconds: "连续恢复窗口（秒）",
  targetWindowsHint: "失败和恢复窗口均为 10–3600 秒；由出口节点根据连续观测判断，保存不会立即变为健康。",
  targetProbe: "目标探测", probeTcp: "TCP 连接探测", probeTcpAuxiliary: "TCP 辅助探测", probeNone: "无主动探测",
  targetProbeHint: "TCP 探测仅说明 TCP 连接能力。关闭主动探测后，仍可根据真实 TCP 连接结果或 UDP 回包观测健康；UDP 无回应保持未知，不因沉默判定故障。",
  udpProbeHint: "辅助 TCP 探测不证明 UDP 可用。UDP 无响应不会自动判定为健康或故障。",
  targetHealth: "目标健康", healthHealthy: "健康", healthSuspect: "可疑", healthRecovering: "恢复中", healthUnhealthy: "故障",
  targetLastChecked: "最近目标观测时间", targetReason: "目标观测原因", targetLastTcp: "TCP 最近连接选中索引", targetLastUdp: "UDP 最近映射选中索引", notApplicable: "不适用",
  targetHealthHint: "健康仅来自当前部署版本的出口观测，与隧道运行就绪分开。索引记录最近一次 TCP 连接或 UDP 映射的选择；最近选中索引不代表所有现有会话正在使用的目标。",
  targetUnknownHint: "未收到可用的当前出口观测，或观测已过期、版本不匹配、配置尚未应用；目标健康显示未知。",
  reasonInitial: "初始状态", reasonSelected: "已选择目标", reasonTargetFailed: "目标连接失败", reasonTargetRecovered: "目标恢复", reasonAllUnavailable: "全部目标不可用",
  targetsCapabilityMissing: "入出口节点都需要支持多目标。请升级两端 Agent 和运行组件，确认均支持 forward.targets.fxp.v1，然后刷新并重新打开编辑器重试。若退回单目标，请保留一项完整目标集。",
  fxpCapabilityMissing: "入出口节点需要支持 FXP。请升级两端 Agent 和运行组件，确认均支持 forward.link.fxp.v1，然后刷新重试。",
  targetSetRequired: "此规则已使用目标集，不能省略后保存为旧版单目标。请重新读取并打开编辑器；退回单目标时删除其余项，保留一项完整目标集后保存。",
  configTooLarge: "完整转发配置超过运行组件的 1 MiB 上限，尚未保存。请减少此连接的规则或目标数量、缩短目标地址，然后重试。",
  clientSourcePolicy: "声明的客户端来源策略", clientSourceOptIn: "显式配置客户端来源（仅 TCP）",
  sourceLegacy: "旧规则：未声明来源策略", sourceSocket: "入口客户端 socket 来源", sourceTrustedProxy: "可信上游 PROXY 来源",
  sourcePolicyHint: "这里只展示期望配置，不代表实际观察到的客户端来源、来源健康或目标已支持 PROXY。",
  sourceKeepHint: "已有来源配置不能省略。关闭后仍提交完整全关配置：不接收 PROXY、可信 CIDR 为空、不发送 PROXY。",
  receiveProxy: "接收可信上游 PROXY", trustedCidrs: "可信上游 CIDR（每行一项）", sendProxy: "向目标发送 PROXY",
  sendProxyOff: "不发送 PROXY", sourceValidation: "请检查来源配置：可信上游须为有效 IPv4/IPv6 CIDR（保存时规范化为网络地址，规范化后不能重复），最多 32 项，不允许 /0 或 IPv4 映射 IPv6；启用接收时至少填写一项，关闭时为空。发送只能为 off、v1 或 v2。",
  sourceReceiveHint: "仅接受直接上游 socket 位于可信 CIDR 中的 PROXY v1/v2。启用后每条连接必须提供有效 PROXY 头，绝对期限 5 秒；v1 最多 108 字节，v2 总长最多 536 字节；不接受任意头部，不回退为普通流量。",
  sourceSendHint: "发送 PROXY v1/v2 前，所有目标服务必须支持对应 PROXY 协议，否则连接会失败。这不是 HTTP 头部注入，不使用 X-Forwarded-For。",
  sourceSocketHint: "关闭接收时使用入口客户端 socket 来源；即使不向目标发送 PROXY，来源仍在隧道内部传递，供 IP 哈希选择使用。",
  clientSourceRequired: "此规则已有客户端来源配置，保存时不能省略。请重新读取并打开编辑器；如需关闭，提交显式全关配置。",
  sourceCapabilityMissing: "客户端来源策略需要节点能力 forward.client-source.fxp.v1。请升级入出口 Agent 和运行组件，确认能力后刷新并重新打开编辑器重试。",
  clientSourceTcpOnly: "客户端来源与 IP 哈希仅支持 TCP，不支持 UDP 或 TCP + UDP。已配置来源时不能切换协议；先明确关闭新规则的来源配置并选择其他策略，或创建新规则。",
  ipHashRequiresClientSource: "IP 哈希需要仅 TCP 且显式客户端来源配置（可全关以使用 socket 来源）。请启用来源配置，或改用其他策略。",
  strategyIpHash: "来源 IP 哈希", ipHashHint: "仅 TCP 且显式声明客户端来源策略时可用；不发送 PROXY 也可按来源 IP 选择。",
  ipHashRemapHint: "IP 哈希不是固定会话绑定；目标池成员或健康可用集合变化可能重新映射新连接，不能保证始终命中同一目标。",
  rateIn: "客户端 → 目标（字节/秒）", rateOut: "目标 → 客户端（字节/秒）", connections: "总并发连接数", perIp: "每个来源 IP 的并发连接数",
  trafficTotals: "历史流量累计", trafficIn: "客户端 → 目标（累计载荷）", trafficOut: "目标 → 客户端（累计载荷）",
  trafficConnections: "累计已接纳连接数", trafficLastReceived: "最近接收统计时间", trafficNotReceived: "尚未收到统计",
  trafficHint: "汇总本规则所有历史来源和日期的载荷字节与已接纳连接（含 UDP 映射）；不是当前速率或并发数，也不代表隧道在线。",
  trafficStale: "统计至少 60 秒未更新；保留历史累计值，不表示当前流量为零。",
  trafficFuture: "统计接收时间晚于本机时钟；保留历史累计值，不据此判断在线。",
  statisticsState: "统计状态", statisticsIdle: "统计空闲", statisticsCollecting: "正在收集统计",
  statisticsBacklogged: "统计积压", statisticsBlocked: "统计受阻", statisticsUnknown: "统计状态未知",
  statisticsLastAck: "最近统计确认", statisticsNoAck: "尚无统计确认",
  statisticsAckHint: "统计确认只表示服务端已持久化接收统计。隧道是否可用仍以当前运行状态为准。",
  statisticsBacklogHint: "统计等待回传或确认；请展开支持详情查看积压。",
  statisticsBlockedHint: "统计收集或回传受阻；请展开支持详情排查。",
  statisticsDetails: "查看统计支持详情", statisticsRotation: "历史统计回收支持",
  statisticsSupported: "支持", statisticsUnsupported: "不支持", statisticsProducers: "统计来源数量",
  statisticsSamples: "统计样本数量", statisticsRules: "统计规则映射数量", statisticsSpool: "统计缓冲占用（字节）",
  noForwards: "此隧道尚未绑定转发规则。", enabled: "启用", suspended: "暂停", suspend: "暂停", resume: "恢复", retry: "重试部署", delete: "删除规则",
  revision: "规则修订", unknown: "未知", statusDraft: "未部署", statusPending: "等待应用", statusDeploying: "正在部署",
  statusActive: "已部署", statusDegraded: "部署异常", statusRetired: "已删除", statusRunning: "运行中", statusPassive: "无业务监听",
  statusError: "应用失败", statusSuspended: "已暂停", statusInactive: "未启用", statusFailed: "失败", statusRetiring: "正在删除", statusBlocked: "部署被阻止",
  disabled: "服务端尚未启用 FXP 隧道，操作未执行。", failed: "操作未确认，请刷新查看实际状态后重试。",
  readFailed: "读取失败，请重试。", conflict: "配置已被其他操作修改。请重新读取并打开编辑表单，再提交。",
  submitted: "请求已完成，状态已重新读取。", reload: "重新读取", code: "原因码", validation: "请检查名称、节点、地址和数值范围。",
  rotateHint: "轮换会重新部署整个隧道，影响以下数量的引用规则，并可能中断已有连接。",
  retireHint: "删除会停止两个节点上的隧道。必须先删除所有引用规则。",
  deleteHint: "删除此规则会停止它的业务监听。其他规则的配置会保留，应用过程中现有连接可能中断。",
  configSaved: "端点已保存，请部署以应用新版本。", target: "转发目标", listener: "业务监听", select: "查看隧道",
} as const;
type CopyKey = keyof typeof zh;
const en: Record<CopyKey, string> = {
  maintenancePreview: "Maintenance preview", previewEndpoints: "Preview endpoint changes", previewKey: "Preview key rotation", previewOperation: "Preview operation",
  previewRun: "Generate preview", previewClose: "Close preview", previewResult: "Read-only maintenance plan", previewCandidate: "Candidate configuration (not saved)",
  previewHint: "Read-only planning only: no configuration save, key rotation or deployment. Online maintenance execution is unavailable; existing endpoint-edit and key-rotation guards still apply.",
  previewPortHint: "Candidate port availability has not been checked and no ports are reserved. Listed ports do not mean ports are available.",
  previewFailed: "Preview failed. No changes were made. Check the inputs or refresh and retry.",
  previewConflict: "The preview snapshot changed. No changes were made. Refresh and generate a new preview.",
  previewDisabled: "FXP tunnel previews are not enabled on the server. No changes were made.",
  previewStale: "The preview expired or no longer matches the snapshot. Generate a new preview; no changes were made.",
  previewExpiry: "Preview expires at", previewHeldPorts: "Currently held ports", previewCandidatePorts: "Candidate ports (not reserved)",
  previewActive: "Desired enabled references", previewSuspended: "Desired suspended references (still included)", previewLiveUnknown: "Live TCP connections and UDP mappings are both unknown; these are not historical totals.",
  previewImpact: "Expected impact (not execution results)", previewTcpNone: "TCP: no expected change impact", previewTcpReconnect: "TCP: reconnect required",
  previewTcpDrain: "TCP: old connections must drain", previewUdpNone: "UDP: no expected change impact", previewUdpRebuild: "UDP: mapping rebuild required",
  previewNoExecutor: "Maintenance execution is unsupported. This plan cannot be executed and does not promise zero downtime.", previewNoChange: "Endpoints are unchanged.",
  previewNotDeployed: "A key-rotation plan requires a deployed tunnel.", previewRuntimeUnconfirmed: "Current runtime is unconfirmed; this cannot authorize maintenance.",
  previewStages: "Planning stages (not executed)", previewReserve: "Reserve candidate ports", previewPrepareEgress: "Prepare exit", previewVerifyEgress: "Verify exit",
  previewCutover: "Cut over entry", previewVerifyIngress: "Verify entry", previewDrain: "Drain old connections", previewRetire: "Retire old deployment", previewRelease: "Release old ports",
  previewChanges: "Changes", previewKeyPreserved: "Key preserved", previewKeyRotated: "Planned key rotation (not rotated)",
  previewRuntimeReady: "Snapshot runtime confirmed (not maintenance support)", previewRuntimeNotReady: "Snapshot runtime not ready", previewRuntimeUnknown: "Snapshot runtime unknown",
  previewTooLarge: "The maintenance preview exceeds the safe display limit (500 references, 2048 held ports). Suspended references are never omitted; no changes were made. Reduce references and retry.",
  previewPendingHint: "Desired-suspended rules may still carry old deployed traffic, especially while suspension is pending or runtime is unconfirmed. Desired reference counts do not prove business listeners have stopped.",
  title: "Encrypted tunnels", subtitle: "Manage reusable entry-to-exit links and carry multiple forwarding rules on each tunnel.",
  create: "Create FXP tunnel", refresh: "Refresh", loading: "Loading tunnels…", empty: "This workspace has no encrypted tunnels.",
  denied: "You do not have permission to read node resources.", readonly: "Your permissions allow viewing only.", workspace: "Select a workspace first.",
  name: "Name", ingress: "Entry node", egress: "Exit node", chooseNode: "Select a node", carrierPort: "Inter-node connection port",
  carrierHint: "Allow the entry node to reach TCP and UDP on this exit-node port. Business listener ports are configured separately.",
  nodesFailed: "Could not read nodes. Refresh and retry.", noNodes: "Two active nodes with suitable roles are required.",
  save: "Save", cancel: "Cancel", working: "Processing…", edit: "Edit endpoints", deploy: "Deploy", rotate: "Rotate key",
  retire: "Delete tunnel", refs: "Referenced rules", desired: "Desired version", applied: "Applied", notApplied: "Not applied",
  generation: "Deployment version", state: "Deployment status", desiredState: "Desired state", appliedVersion: "Applied configuration version", actionDenied: "Your permissions do not allow this operation.", lease: "Runtime lease expires", expired: "Lease expired", leaseUnknown: "Lease status unknown",
  noDeployment: "Not deployed", passiveHint: "The applied configuration contains no enabled entry rules.", ackHint: "Apply acknowledgements record the latest configuration application. Current runtime state comes from node observations.",
  errorDetails: "View error details", updateHint: "Saving or changing a rule reapplies the tunnel. Existing connections may be interrupted. Check the status and retry if application fails.",
  deploymentState: "Current deployment", statusPolicyBlocked: "Deployment blocked by workspace policy",
  policyBlockedHint: "Current authorization or traffic policies prevent further tunnel use, so the runtime lease will not renew. Check workspace authorization and traffic allowance. Once the policy permits use again, the system will reapply the configuration.",
  zeroRefs: "Tunnel deletion and key rotation require zero references. Suspended rules still count.",
  endpointRetire: "This tunnel has been deployed. Delete it and create a new tunnel before changing endpoints or the connection port.",
  rotateZeroRefs: "Delete all referenced rules before rotating the key to avoid affecting traffic during the two-node switch.",
  appliedAck: "Apply acknowledgement", runtimeState: "Current runtime state", stale: "Runtime facts are stale", passiveDesired: "No-listener configuration applied",
  passiveLive: "Entry standing by: no enabled rules", exited: "Exited", closed: "Stopped", removed: "Removed", mismatch: "Runtime configuration differs from desired", absent: "No runtime instance observed",
  addForward: "Add forwarding rule", editForward: "Edit forwarding rule", protocol: "Business protocol", protocolLocked: "Create a new rule to change its protocol or listen scope. The business port can be edited.",
  listenPort: "Business listener port", listenHost: "Listen scope", wildcard: "All addresses", loopback4: "Local IPv4 only", loopback6: "Local IPv6 only",
  targetHost: "Target address", targetPort: "Target port", limits: "Rule limits", limitHint: "0 means no rule-specific limit. Workspace policies still apply.",
  targets: "Target set", targetsOptIn: "Enable multiple target selection", targetsLegacy: "Legacy single target",
  targetsLegacyHint: "Keep the legacy single target by default. Opt in to configure target order, selection and probing.",
  targetsHint: "Keep 1–10 distinct address and port pairs in order. The first item always supplies this rule's primary target fields.",
  targetAddressHint: "Enter address and port separately, such as www.example.com and 443. Use raw IPv6 such as 2001:db8::1 without brackets. Backslashes and addresses with a port are not accepted.",
  targetsKeepSetHint: "This rule already uses a target set. To return to one target, remove the other items and save the complete set with one item.",
  targetsValidation: "Check the form: use 1–10 distinct address and port pairs. Addresses cannot contain backslashes, brackets or a port; IPv6 must be a valid raw address. Ports accept 1–65535; failure and recovery windows accept integer seconds from 10–3600.",
  targetIndex: "Target index", targetFirst: "First item", addTarget: "Add target", removeTarget: "Remove target", moveTargetUp: "Move up", moveTargetDown: "Move down",
  targetStrategy: "Selection strategy", strategyFallback: "Ordered fallback", strategyRoundRobin: "Round robin", strategyRandom: "Random",
  targetFailureSeconds: "Consecutive failure window (seconds)", targetRecoverSeconds: "Consecutive recovery window (seconds)",
  targetWindowsHint: "Both windows accept 10–3600 seconds. The exit node evaluates consecutive observations; saving does not immediately establish health.",
  targetProbe: "Target probe", probeTcp: "TCP connection probe", probeTcpAuxiliary: "Auxiliary TCP probe", probeNone: "No active probe",
  targetProbeHint: "A TCP probe only demonstrates TCP connectivity. With active probing disabled, actual TCP connection results or UDP replies can still provide health evidence. UDP silence remains unknown and does not establish failure.",
  udpProbeHint: "Auxiliary TCP probing does not prove UDP availability. UDP silence does not automatically establish health or failure.",
  targetHealth: "Target health", healthHealthy: "Healthy", healthSuspect: "Suspect", healthRecovering: "Recovering", healthUnhealthy: "Unhealthy",
  targetLastChecked: "Last target observation", targetReason: "Target observation reason", targetLastTcp: "TCP last connection target index", targetLastUdp: "UDP last mapping target index", notApplicable: "Not applicable",
  targetHealthHint: "Health comes only from exit observations for the current deployment and is separate from runtime readiness. Indices record the most recent TCP connection or UDP mapping choice; they do not describe every existing session's target.",
  targetUnknownHint: "Current exit observations are unavailable, stale, mismatched, or the configuration is not applied yet. Target health is unknown.",
  reasonInitial: "Initial state", reasonSelected: "Target selected", reasonTargetFailed: "Target connection failed", reasonTargetRecovered: "Target recovered", reasonAllUnavailable: "All targets unavailable",
  targetsCapabilityMissing: "Both entry and exit nodes need multi-target support. Upgrade both Agents and runtimes, confirm forward.targets.fxp.v1 on each, then refresh and reopen the editor to retry. To return to one target, keep a complete set with one item.",
  fxpCapabilityMissing: "Both entry and exit nodes need FXP support. Upgrade both Agents and runtimes, confirm forward.link.fxp.v1 on each, then refresh and retry.",
  targetSetRequired: "This rule already uses a target set and cannot be saved as legacy by omitting it. Reload and reopen the editor. To return to one target, remove the other items and save a complete set with one item.",
  configTooLarge: "The complete forwarding configuration exceeds the runtime's 1 MiB limit and was not saved. Reduce rules or targets on this tunnel, or shorten target addresses, then retry.",
  clientSourcePolicy: "Declared client source policy", clientSourceOptIn: "Declare client source policy (TCP only)",
  sourceLegacy: "Legacy: source policy not declared", sourceSocket: "Entry client socket source", sourceTrustedProxy: "Trusted upstream PROXY source",
  sourcePolicyHint: "This is desired configuration, not observed client identity, source health, or proof that targets support PROXY.",
  sourceKeepHint: "An existing source config cannot be omitted. Disabling still submits a complete all-off config: receive off, empty trusted CIDRs, send off.",
  receiveProxy: "Receive trusted upstream PROXY", trustedCidrs: "Trusted upstream CIDRs (one per line)", sendProxy: "Send PROXY to targets",
  sendProxyOff: "Do not send PROXY", sourceValidation: "Check the source policy: use valid IPv4/IPv6 CIDRs (masked to canonical networks on save, with no duplicate networks), at most 32, never /0 or IPv4-mapped IPv6. Receiving requires at least one trusted CIDR; keep the list empty when receiving is off. Sending must be off, v1 or v2.",
  sourceReceiveHint: "Accept PROXY v1/v2 only from a direct upstream socket in the trusted CIDRs. Every connection must supply a valid PROXY header within an absolute 5-second deadline; v1 is capped at 108 bytes and v2 at 536 total bytes; no arbitrary headers or fallback to plain traffic.",
  sourceSendHint: "Every destination service MUST support the selected PROXY v1/v2 protocol before sending it, or connections will fail. This is not HTTP header injection and does not use X-Forwarded-For.",
  sourceSocketHint: "When receiving is off, use the entry client socket source. Even with PROXY sending off, the source is carried internally through the tunnel for IP-hash selection.",
  clientSourceRequired: "This rule already has client source configuration and cannot omit it on save. Reload and reopen the editor; to disable it, submit an explicit all-off config.",
  sourceCapabilityMissing: "Client source policy requires node capability forward.client-source.fxp.v1. Upgrade the entry and exit Agents and runtimes, confirm the capability, then refresh and reopen the editor to retry.",
  clientSourceTcpOnly: "Client source and IP hash support TCP only, not UDP or TCP + UDP. A configured source policy blocks protocol changes. Explicitly disable source on a new rule and choose another strategy first, or create a new rule.",
  ipHashRequiresClientSource: "IP hash requires TCP only and explicit client source configuration (all-off is valid for socket source). Enable source policy or choose another strategy.",
  strategyIpHash: "Source IP hash", ipHashHint: "Available only for TCP with an explicit client source policy; IP-based selection works even when PROXY sending is off.",
  ipHashRemapHint: "IP hash is not fixed session affinity. Pool membership or the healthy eligible target set changing can remap new connections; the same target is not guaranteed.",
  rateIn: "Client → target (bytes/sec)", rateOut: "Target → client (bytes/sec)", connections: "Total concurrent connections", perIp: "Concurrent connections per source IP",
  trafficTotals: "Historical traffic totals", trafficIn: "Client → target (total payload)", trafficOut: "Target → client (total payload)",
  trafficConnections: "Total admitted connections", trafficLastReceived: "Last statistics received at", trafficNotReceived: "Not received",
  trafficHint: "Payload bytes and admitted connections (including UDP mappings) summed across all historical producers and days for this rule. Not current rates or concurrency, and not evidence that the tunnel is online.",
  trafficStale: "Statistics have not updated for at least 60 seconds. Historical totals are retained; this does not mean current traffic is zero.",
  trafficFuture: "The statistics receipt is ahead of this device's clock. Historical totals are retained; this is not evidence that the tunnel is online.",
  statisticsState: "Statistics status", statisticsIdle: "Statistics idle", statisticsCollecting: "Collecting statistics",
  statisticsBacklogged: "Statistics backlogged", statisticsBlocked: "Statistics blocked", statisticsUnknown: "Statistics status unknown",
  statisticsLastAck: "Last statistics acknowledgement", statisticsNoAck: "No statistics acknowledgement yet",
  statisticsAckHint: "A statistics acknowledgement means the server durably received statistics. Tunnel availability still comes from current runtime state.",
  statisticsBacklogHint: "Statistics are waiting for upload or acknowledgement. Expand support details to inspect the backlog.",
  statisticsBlockedHint: "Statistics collection or upload is blocked. Expand support details to investigate.",
  statisticsDetails: "View statistics support details", statisticsRotation: "Historical statistics rotation supported",
  statisticsSupported: "Supported", statisticsUnsupported: "Unsupported", statisticsProducers: "Statistics producers",
  statisticsSamples: "Statistics samples", statisticsRules: "Statistics rule mappings", statisticsSpool: "Statistics spool bytes",
  noForwards: "No forwarding rules are bound to this tunnel.", enabled: "Enabled", suspended: "Suspended", suspend: "Suspend", resume: "Resume", retry: "Retry deployment", delete: "Delete rule",
  revision: "Rule revision", unknown: "Unknown", statusDraft: "Not deployed", statusPending: "Pending apply", statusDeploying: "Deploying",
  statusActive: "Deployed", statusDegraded: "Deployment degraded", statusRetired: "Deleted", statusRunning: "Running", statusPassive: "No business listener",
  statusError: "Apply failed", statusSuspended: "Suspended", statusInactive: "Disabled", statusFailed: "Failed", statusRetiring: "Deleting", statusBlocked: "Deployment blocked",
  disabled: "FXP tunnels are not enabled on the server. The operation was not performed.", failed: "The operation is unconfirmed. Refresh to check the actual state before retrying.",
  readFailed: "Could not load data. Retry.", conflict: "Another operation changed this configuration. Reload and reopen the editor before submitting.",
  submitted: "Request completed; status reloaded.", reload: "Reload", code: "Reason code", validation: "Check the name, nodes, addresses and numeric ranges.",
  rotateHint: "Rotation redeploys the entire tunnel and affects this number of referenced rules. Existing connections may be interrupted.",
  retireHint: "Deletion stops the tunnel on both nodes. Delete all referenced rules first.",
  deleteHint: "Deletion stops this rule's business listener. Other rule configurations remain. Existing connections may be interrupted during application.",
  configSaved: "Endpoints saved. Deploy to apply the new version.", target: "Forwarding target", listener: "Business listener", select: "View tunnel",
};
export type LinksCopy = Record<CopyKey, string>;
export function linksCopy(locale: Locale): LinksCopy { return locale === "en" ? en : zh; }
