import type { Locale } from "@/lib/i18n";

const zh = {
  title: "加密隧道", subtitle: "管理可复用的入出口连接，在同一隧道中承载多条转发规则。",
  create: "创建 FXP 隧道", refresh: "刷新", loading: "正在读取隧道…", empty: "当前工作空间还没有加密隧道。",
  denied: "没有读取节点资源的权限。", readonly: "当前权限只允许查看隧道。", workspace: "请先选择工作空间。",
  name: "名称", ingress: "入口节点", egress: "出口节点", chooseNode: "选择节点", carrierPort: "节点间连接端口",
  carrierHint: "此端口位于出口节点，需允许入口节点访问 TCP 和 UDP；与业务监听端口分别设置。",
  nodesFailed: "节点列表读取失败，请刷新后重试。", noNodes: "需要两个角色合适且生命周期为启用的节点。",
  save: "保存", cancel: "取消", working: "正在处理…", edit: "编辑端点", deploy: "部署", rotate: "轮换密钥",
  retire: "删除隧道", refs: "引用规则", desired: "期望版本", applied: "已应用", notApplied: "尚未应用",
  generation: "部署版本", state: "部署状态", desiredState: "期望状态", appliedVersion: "已应用配置版本", actionDenied: "当前权限不允许此操作。", lease: "运行租约到期", expired: "租约已过期", leaseUnknown: "租约状态未知",
  noDeployment: "尚未部署", passiveHint: "已应用的配置中，入口没有启用的转发规则。", ackHint: "应用回执记录最近一次配置应用。当前运行状态以节点事实为准。",
  errorDetails: "查看错误详情", updateHint: "保存或调整规则会触发隧道重新应用，现有连接可能中断。应用失败时，请查看状态并重试。",
  deploymentState: "当前部署", statusPolicyBlocked: "工作空间策略阻止部署",
  policyBlockedHint: "当前授权或流量策略不允许继续使用隧道，运行租约不会续期。请检查工作空间授权和流量额度；策略恢复后，系统会重新应用配置。",
  zeroRefs: "删除隧道和轮换密钥仅允许零引用；暂停的规则仍计入引用。",
  endpointRetire: "隧道已部署。修改端点或连接端口前，先删除此隧道并创建新的隧道。",
  rotateZeroRefs: "轮换密钥前请先删除全部引用规则，避免两个节点分步切换影响业务。",
  appliedAck: "应用回执", runtimeState: "当前运行状态", stale: "运行事实已过期", passiveDesired: "已应用无业务监听配置",
  passiveLive: "入口待命：没有启用的规则", exited: "已退出", closed: "已停止", removed: "已移除", mismatch: "运行配置与期望不一致", absent: "未发现运行实例",
  addForward: "添加转发规则", editForward: "编辑转发规则", protocol: "业务协议", protocolLocked: "修改协议或监听范围需创建新规则；业务端口可以修改。",
  listenPort: "业务监听端口", listenHost: "监听范围", wildcard: "所有地址", loopback4: "仅本机 IPv4", loopback6: "仅本机 IPv6",
  targetHost: "目标地址", targetPort: "目标端口", limits: "本规则限额", limitHint: "0 表示本规则不限；仍受工作空间策略约束。",
  targets: "目标集", targetsOptIn: "启用多目标选择", targetsLegacy: "旧版单目标",
  targetsLegacyHint: "默认保留旧版单目标。主动启用后，才能配置目标顺序、选择策略和探测。",
  targetsHint: "按顺序配置 1–10 个不重复的地址与端口。首项始终同步为本规则的首选目标。",
  targetAddressHint: "地址与端口分开填写，如 www.example.com 和 443。IPv6 使用原始地址，如 2001:db8::1，不加方括号；不接受反斜杠或带端口的地址。",
  targetsKeepSetHint: "此规则已使用目标集。退回单目标时删除其余项，保留一项并保存完整目标集。",
  targetsValidation: "请检查表单：目标集需有 1–10 个不重复的地址与端口，地址不能带反斜杠、方括号或端口，IPv6 需为有效原始地址；端口为 1–65535，失败和恢复窗口为 10–3600 的整数秒。",
  targetIndex: "目标索引", targetFirst: "首项", addTarget: "添加目标", removeTarget: "删除目标", moveTargetUp: "上移", moveTargetDown: "下移",
  targetStrategy: "选择策略", strategyFallback: "按序回退", strategyRoundRobin: "轮询", strategyRandom: "随机",
  targetFailureSeconds: "连续失败窗口（秒）", targetRecoverSeconds: "连续恢复窗口（秒）",
  targetWindowsHint: "失败和恢复窗口均为 10–3600 秒；由出口节点根据连续观测判断，保存不会立即变为健康。",
  targetProbe: "目标探测", probeTcp: "TCP 连接探测", probeTcpAuxiliary: "TCP 辅助探测", probeNone: "无主动探测",
  targetProbeHint: "TCP 探测仅说明 TCP 连接能力。关闭主动探测后，仍可根据真实 TCP 连接结果或 UDP 回包观测健康；UDP 无回应保持未知，不因沉默判定故障。",
  udpProbeHint: "辅助 TCP 探测不证明 UDP 可用。UDP 无响应不会自动判定为健康或故障。",
  targetHealth: "目标健康", healthHealthy: "健康", healthSuspect: "可疑", healthRecovering: "恢复中", healthUnhealthy: "故障",
  targetLastChecked: "最近目标观测时间", targetReason: "目标观测原因", targetLastTcp: "TCP 最近连接选中索引", targetLastUdp: "UDP 最近映射选中索引", notApplicable: "不适用",
  targetHealthHint: "健康仅来自当前部署版本的出口观测，与隧道运行就绪分开。索引记录最近一次 TCP 连接或 UDP 映射的选择；最近选中索引不代表所有现有会话正在使用的目标。",
  targetUnknownHint: "未收到可用的当前出口观测，或观测已过期、版本不匹配、配置尚未应用；目标健康显示未知。",
  reasonInitial: "初始状态", reasonSelected: "已选择目标", reasonTargetFailed: "目标连接失败", reasonTargetRecovered: "目标恢复", reasonAllUnavailable: "全部目标不可用",
  targetsCapabilityMissing: "入出口节点都需要支持多目标。请升级两端 Agent 和运行组件，确认均支持 forward.targets.fxp.v1，然后刷新并重新打开编辑器重试。若退回单目标，请保留一项完整目标集。",
  fxpCapabilityMissing: "入出口节点需要支持 FXP。请升级两端 Agent 和运行组件，确认均支持 forward.link.fxp.v1，然后刷新重试。",
  targetSetRequired: "此规则已使用目标集，不能省略后保存为旧版单目标。请重新读取并打开编辑器；退回单目标时删除其余项，保留一项完整目标集后保存。",
  configTooLarge: "完整转发配置超过运行组件的 1 MiB 上限，尚未保存。请减少此连接的规则或目标数量、缩短目标地址，然后重试。",
  rateIn: "客户端 → 目标（字节/秒）", rateOut: "目标 → 客户端（字节/秒）", connections: "总并发连接数", perIp: "每个来源 IP 的并发连接数",
  trafficTotals: "历史流量累计", trafficIn: "客户端 → 目标（累计载荷）", trafficOut: "目标 → 客户端（累计载荷）",
  trafficConnections: "累计已接纳连接数", trafficLastReceived: "最近接收统计时间", trafficNotReceived: "尚未收到统计",
  trafficHint: "汇总本规则所有历史来源和日期的载荷字节与已接纳连接（含 UDP 映射）；不是当前速率或并发数，也不代表隧道在线。",
  trafficStale: "统计至少 60 秒未更新；保留历史累计值，不表示当前流量为零。",
  trafficFuture: "统计接收时间晚于本机时钟；保留历史累计值，不据此判断在线。",
  statisticsState: "统计状态", statisticsIdle: "统计空闲", statisticsCollecting: "正在收集统计",
  statisticsBacklogged: "统计积压", statisticsBlocked: "统计受阻", statisticsUnknown: "统计状态未知",
  statisticsLastAck: "最近统计确认", statisticsNoAck: "尚无统计确认",
  statisticsAckHint: "统计确认只表示服务端已持久化接收统计。隧道是否可用仍以当前运行状态为准。",
  statisticsBacklogHint: "统计等待回传或确认；请展开支持详情查看积压。",
  statisticsBlockedHint: "统计收集或回传受阻；请展开支持详情排查。",
  statisticsDetails: "查看统计支持详情", statisticsRotation: "历史统计回收支持",
  statisticsSupported: "支持", statisticsUnsupported: "不支持", statisticsProducers: "统计来源数量",
  statisticsSamples: "统计样本数量", statisticsRules: "统计规则映射数量", statisticsSpool: "统计缓冲占用（字节）",
  noForwards: "此隧道尚未绑定转发规则。", enabled: "启用", suspended: "暂停", suspend: "暂停", resume: "恢复", retry: "重试部署", delete: "删除规则",
  revision: "规则修订", unknown: "未知", statusDraft: "未部署", statusPending: "等待应用", statusDeploying: "正在部署",
  statusActive: "已部署", statusDegraded: "部署异常", statusRetired: "已删除", statusRunning: "运行中", statusPassive: "无业务监听",
  statusError: "应用失败", statusSuspended: "已暂停", statusInactive: "未启用", statusFailed: "失败", statusRetiring: "正在删除", statusBlocked: "部署被阻止",
  disabled: "服务端尚未启用 FXP 隧道，操作未执行。", failed: "操作未确认，请刷新查看实际状态后重试。",
  readFailed: "读取失败，请重试。", conflict: "配置已被其他操作修改。请重新读取并打开编辑表单，再提交。",
  submitted: "请求已完成，状态已重新读取。", reload: "重新读取", code: "原因码", validation: "请检查名称、节点、地址和数值范围。",
  rotateHint: "轮换会重新部署整个隧道，影响以下数量的引用规则，并可能中断已有连接。",
  retireHint: "删除会停止两个节点上的隧道。必须先删除所有引用规则。",
  deleteHint: "删除此规则会停止它的业务监听。其他规则的配置会保留，应用过程中现有连接可能中断。",
  configSaved: "端点已保存，请部署以应用新版本。", target: "转发目标", listener: "业务监听", select: "查看隧道",
} as const;
type CopyKey = keyof typeof zh;
const en: Record<CopyKey, string> = {
  title: "Encrypted tunnels", subtitle: "Manage reusable entry-to-exit links and carry multiple forwarding rules on each tunnel.",
  create: "Create FXP tunnel", refresh: "Refresh", loading: "Loading tunnels…", empty: "This workspace has no encrypted tunnels.",
  denied: "You do not have permission to read node resources.", readonly: "Your permissions allow viewing only.", workspace: "Select a workspace first.",
  name: "Name", ingress: "Entry node", egress: "Exit node", chooseNode: "Select a node", carrierPort: "Inter-node connection port",
  carrierHint: "Allow the entry node to reach TCP and UDP on this exit-node port. Business listener ports are configured separately.",
  nodesFailed: "Could not read nodes. Refresh and retry.", noNodes: "Two active nodes with suitable roles are required.",
  save: "Save", cancel: "Cancel", working: "Processing…", edit: "Edit endpoints", deploy: "Deploy", rotate: "Rotate key",
  retire: "Delete tunnel", refs: "Referenced rules", desired: "Desired version", applied: "Applied", notApplied: "Not applied",
  generation: "Deployment version", state: "Deployment status", desiredState: "Desired state", appliedVersion: "Applied configuration version", actionDenied: "Your permissions do not allow this operation.", lease: "Runtime lease expires", expired: "Lease expired", leaseUnknown: "Lease status unknown",
  noDeployment: "Not deployed", passiveHint: "The applied configuration contains no enabled entry rules.", ackHint: "Apply acknowledgements record the latest configuration application. Current runtime state comes from node observations.",
  errorDetails: "View error details", updateHint: "Saving or changing a rule reapplies the tunnel. Existing connections may be interrupted. Check the status and retry if application fails.",
  deploymentState: "Current deployment", statusPolicyBlocked: "Deployment blocked by workspace policy",
  policyBlockedHint: "Current authorization or traffic policies prevent further tunnel use, so the runtime lease will not renew. Check workspace authorization and traffic allowance. Once the policy permits use again, the system will reapply the configuration.",
  zeroRefs: "Tunnel deletion and key rotation require zero references. Suspended rules still count.",
  endpointRetire: "This tunnel has been deployed. Delete it and create a new tunnel before changing endpoints or the connection port.",
  rotateZeroRefs: "Delete all referenced rules before rotating the key to avoid affecting traffic during the two-node switch.",
  appliedAck: "Apply acknowledgement", runtimeState: "Current runtime state", stale: "Runtime facts are stale", passiveDesired: "No-listener configuration applied",
  passiveLive: "Entry standing by: no enabled rules", exited: "Exited", closed: "Stopped", removed: "Removed", mismatch: "Runtime configuration differs from desired", absent: "No runtime instance observed",
  addForward: "Add forwarding rule", editForward: "Edit forwarding rule", protocol: "Business protocol", protocolLocked: "Create a new rule to change its protocol or listen scope. The business port can be edited.",
  listenPort: "Business listener port", listenHost: "Listen scope", wildcard: "All addresses", loopback4: "Local IPv4 only", loopback6: "Local IPv6 only",
  targetHost: "Target address", targetPort: "Target port", limits: "Rule limits", limitHint: "0 means no rule-specific limit. Workspace policies still apply.",
  targets: "Target set", targetsOptIn: "Enable multiple target selection", targetsLegacy: "Legacy single target",
  targetsLegacyHint: "Keep the legacy single target by default. Opt in to configure target order, selection and probing.",
  targetsHint: "Keep 1–10 distinct address and port pairs in order. The first item always supplies this rule's primary target fields.",
  targetAddressHint: "Enter address and port separately, such as www.example.com and 443. Use raw IPv6 such as 2001:db8::1 without brackets. Backslashes and addresses with a port are not accepted.",
  targetsKeepSetHint: "This rule already uses a target set. To return to one target, remove the other items and save the complete set with one item.",
  targetsValidation: "Check the form: use 1–10 distinct address and port pairs. Addresses cannot contain backslashes, brackets or a port; IPv6 must be a valid raw address. Ports accept 1–65535; failure and recovery windows accept integer seconds from 10–3600.",
  targetIndex: "Target index", targetFirst: "First item", addTarget: "Add target", removeTarget: "Remove target", moveTargetUp: "Move up", moveTargetDown: "Move down",
  targetStrategy: "Selection strategy", strategyFallback: "Ordered fallback", strategyRoundRobin: "Round robin", strategyRandom: "Random",
  targetFailureSeconds: "Consecutive failure window (seconds)", targetRecoverSeconds: "Consecutive recovery window (seconds)",
  targetWindowsHint: "Both windows accept 10–3600 seconds. The exit node evaluates consecutive observations; saving does not immediately establish health.",
  targetProbe: "Target probe", probeTcp: "TCP connection probe", probeTcpAuxiliary: "Auxiliary TCP probe", probeNone: "No active probe",
  targetProbeHint: "A TCP probe only demonstrates TCP connectivity. With active probing disabled, actual TCP connection results or UDP replies can still provide health evidence. UDP silence remains unknown and does not establish failure.",
  udpProbeHint: "Auxiliary TCP probing does not prove UDP availability. UDP silence does not automatically establish health or failure.",
  targetHealth: "Target health", healthHealthy: "Healthy", healthSuspect: "Suspect", healthRecovering: "Recovering", healthUnhealthy: "Unhealthy",
  targetLastChecked: "Last target observation", targetReason: "Target observation reason", targetLastTcp: "TCP last connection target index", targetLastUdp: "UDP last mapping target index", notApplicable: "Not applicable",
  targetHealthHint: "Health comes only from exit observations for the current deployment and is separate from runtime readiness. Indices record the most recent TCP connection or UDP mapping choice; they do not describe every existing session's target.",
  targetUnknownHint: "Current exit observations are unavailable, stale, mismatched, or the configuration is not applied yet. Target health is unknown.",
  reasonInitial: "Initial state", reasonSelected: "Target selected", reasonTargetFailed: "Target connection failed", reasonTargetRecovered: "Target recovered", reasonAllUnavailable: "All targets unavailable",
  targetsCapabilityMissing: "Both entry and exit nodes need multi-target support. Upgrade both Agents and runtimes, confirm forward.targets.fxp.v1 on each, then refresh and reopen the editor to retry. To return to one target, keep a complete set with one item.",
  fxpCapabilityMissing: "Both entry and exit nodes need FXP support. Upgrade both Agents and runtimes, confirm forward.link.fxp.v1 on each, then refresh and retry.",
  targetSetRequired: "This rule already uses a target set and cannot be saved as legacy by omitting it. Reload and reopen the editor. To return to one target, remove the other items and save a complete set with one item.",
  configTooLarge: "The complete forwarding configuration exceeds the runtime's 1 MiB limit and was not saved. Reduce rules or targets on this tunnel, or shorten target addresses, then retry.",
  rateIn: "Client → target (bytes/sec)", rateOut: "Target → client (bytes/sec)", connections: "Total concurrent connections", perIp: "Concurrent connections per source IP",
  trafficTotals: "Historical traffic totals", trafficIn: "Client → target (total payload)", trafficOut: "Target → client (total payload)",
  trafficConnections: "Total admitted connections", trafficLastReceived: "Last statistics received at", trafficNotReceived: "Not received",
  trafficHint: "Payload bytes and admitted connections (including UDP mappings) summed across all historical producers and days for this rule. Not current rates or concurrency, and not evidence that the tunnel is online.",
  trafficStale: "Statistics have not updated for at least 60 seconds. Historical totals are retained; this does not mean current traffic is zero.",
  trafficFuture: "The statistics receipt is ahead of this device's clock. Historical totals are retained; this is not evidence that the tunnel is online.",
  statisticsState: "Statistics status", statisticsIdle: "Statistics idle", statisticsCollecting: "Collecting statistics",
  statisticsBacklogged: "Statistics backlogged", statisticsBlocked: "Statistics blocked", statisticsUnknown: "Statistics status unknown",
  statisticsLastAck: "Last statistics acknowledgement", statisticsNoAck: "No statistics acknowledgement yet",
  statisticsAckHint: "A statistics acknowledgement means the server durably received statistics. Tunnel availability still comes from current runtime state.",
  statisticsBacklogHint: "Statistics are waiting for upload or acknowledgement. Expand support details to inspect the backlog.",
  statisticsBlockedHint: "Statistics collection or upload is blocked. Expand support details to investigate.",
  statisticsDetails: "View statistics support details", statisticsRotation: "Historical statistics rotation supported",
  statisticsSupported: "Supported", statisticsUnsupported: "Unsupported", statisticsProducers: "Statistics producers",
  statisticsSamples: "Statistics samples", statisticsRules: "Statistics rule mappings", statisticsSpool: "Statistics spool bytes",
  noForwards: "No forwarding rules are bound to this tunnel.", enabled: "Enabled", suspended: "Suspended", suspend: "Suspend", resume: "Resume", retry: "Retry deployment", delete: "Delete rule",
  revision: "Rule revision", unknown: "Unknown", statusDraft: "Not deployed", statusPending: "Pending apply", statusDeploying: "Deploying",
  statusActive: "Deployed", statusDegraded: "Deployment degraded", statusRetired: "Deleted", statusRunning: "Running", statusPassive: "No business listener",
  statusError: "Apply failed", statusSuspended: "Suspended", statusInactive: "Disabled", statusFailed: "Failed", statusRetiring: "Deleting", statusBlocked: "Deployment blocked",
  disabled: "FXP tunnels are not enabled on the server. The operation was not performed.", failed: "The operation is unconfirmed. Refresh to check the actual state before retrying.",
  readFailed: "Could not load data. Retry.", conflict: "Another operation changed this configuration. Reload and reopen the editor before submitting.",
  submitted: "Request completed; status reloaded.", reload: "Reload", code: "Reason code", validation: "Check the name, nodes, addresses and numeric ranges.",
  rotateHint: "Rotation redeploys the entire tunnel and affects this number of referenced rules. Existing connections may be interrupted.",
  retireHint: "Deletion stops the tunnel on both nodes. Delete all referenced rules first.",
  deleteHint: "Deletion stops this rule's business listener. Other rule configurations remain. Existing connections may be interrupted during application.",
  configSaved: "Endpoints saved. Deploy to apply the new version.", target: "Forwarding target", listener: "Business listener", select: "View tunnel",
};
export type LinksCopy = Record<CopyKey, string>;
export function linksCopy(locale: Locale): LinksCopy { return locale === "en" ? en : zh; }
